version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - cd ./my-app
      - |
        if [ -z "$BRANCH_NAME" ]; then
          BRANCH_NAME=`git branch --contains | grep -v '(no branch)' | cut -b 3-`
        fi
      - echo $BRANCH_NAME
      #- mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      #- mvn package
artifacts:
  files:
    - my-app/target/my-app-1.0-SNAPSHOT.jar
  discard-paths: yes